export const adsData = [
  {
    id: '1',
    title: 'Ракетка для большого тенниса Triumph Pro ST',
    price: '2 200 ₽',
    place: 'Санкт Петербург',
    date: 'Сегодня в 10:45',
  },
  {
    id: '2',
    title: 'Ракетка для большого тенниса Triumph Pro ST',
    price: '2 200 ₽',
    place: 'Санкт Петербург',
    date: 'Сегодня в 10:45',
  },
  {
    id: '3',
    title: 'Ракетка для большого тенниса Triumph Pro ST',
    price: '2 200 ₽',
    place: 'Санкт Петербург',
    date: 'Сегодня в 10:45',
  },
  {
    id: '4',
    title: 'Ракетка для большого тенниса Triumph Pro ST',
    price: '2 200 ₽',
    place: 'Санкт Петербург',
    date: 'Сегодня в 10:45',
  },
  {
    id: '5',
    title: 'Ракетка для большого тенниса Triumph Pro ST',
    price: '2 200 ₽',
    place: 'Санкт Петербург',
    date: 'Сегодня в 10:45',
  },
  {
    id: '6',
    title: 'Ракетка для большого тенниса Triumph Pro ST',
    price: '2 200 ₽',
    place: 'Санкт Петербург',
    date: 'Сегодня в 10:45',
  },
  {
    id: '7',
    title: 'Ракетка для большого тенниса Triumph Pro ST',
    price: '2 200 ₽',
    place: 'Санкт Петербург',
    date: 'Сегодня в 10:45',
  },
  {
    id: '8',
    title: 'Ракетка для большого тенниса Triumph Pro ST',
    price: '2 200 ₽',
    place: 'Санкт Петербург',
    date: 'Сегодня в 10:45',
  },
]
